hash-format = "sha256"

[[files]]
file = "allium/hangman/main.lua"

[[files]]
file = "allium/hangman/manifest.json"

[[files]]
file = "allium/hangman/words.lua"

[[files]]
file = "config/ChineseIME/config.json"

[[files]]
file = "config/ballotbox.toml"

[[files]]
file = "config/bobby-block-entity-allowlist.conf"

[[files]]
file = "config/bobby.conf"

[[files]]
file = "config/canary.json"

[[files]]
file = "config/emi.css"

[[files]]
file = "config/fabric_loader_dependencies.json"

[[files]]
file = "config/fireblanket/fireblanket.txt"

[[files]]
file = "config/glowcase.toml"

[[files]]
file = "config/hoofprint.toml"

[[files]]
file = "config/lmft.json"

[[files]]
file = "config/meret.toml"

[[files]]
file = "config/modfest_sync/behaviour.properties"

[[files]]
file = "config/modmenu.json"

[[files]]
file = "config/quickerconnectbutton.json5"

[[files]]
file = "config/rocks.json"

[[files]]
file = "config/roles.json"

[[files]]
file = "config/simpleupdatechecker_modpack.json"

[[files]]
file = "config/sodium-options.json"

[[files]]
file = "config/sounds/chat.json"

[[files]]
file = "config/stfu.json5"

[[files]]
file = "config/styled-chat.json"

[[files]]
file = "config/styled-nicknames.json"

[[files]]
file = "config/styled_chat_emoji.json"

[[files]]
file = "config/styledplayerlist/config.json"

[[files]]
file = "config/styledplayerlist/styles/default.json"

[[files]]
file = "config/surveyor.toml"

[[files]]
file = "config/waila/blacklist.json5"

[[files]]
file = "config/waila/waila.json5"

[[files]]
file = "config/waila/waila_plugins.json5"

[[files]]
file = "config/yosbr/options.txt"

[[files]]
file = "jsonpatcher/global_patches/assets/gen_assets.jsonpatch"

[[files]]
file = "jsonpatcher/scripts/make_items.jsonpatch"

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/armorstandeditor.pw.toml"
metafile = true

[[files]]
file = "mods/axiom-client.pw.toml"
metafile = true

[[files]]
file = "mods/axiom-server.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/badstdout.pw.toml"
metafile = true

[[files]]
file = "mods/better-narrator-error.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/cantilever.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/eiv.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/floralie.pw.toml"
metafile = true

[[files]]
file = "mods/hoofprint.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/item-descriptions.pw.toml"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lmft.pw.toml"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
metafile = true

[[files]]
file = "mods/player-roles.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/scattered-shards.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/simple-resource-loader.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/spawnanywhere.pw.toml"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
metafile = true

[[files]]
file = "mods/surveyor.pw.toml"
metafile = true

[[files]]
file = "mods/tmyk.pw.toml"
metafile = true

[[files]]
file = "mods/worldedit-client.toml"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
metafile = true

[[files]]
file = "mods/worldedit-server.pw.toml"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "resources/resourcepack/required/Unsanded-1.1.1-custom.zip"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/glowcase/lang/en_us.json"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/16x/mod-garden/generic/icon-background.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/16x/mod-garden/generic/icon.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/16x/mod-garden/generic/logo-small-outline.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/16x/mod-garden/generic/logo-small.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/16x/mod-garden/nature/icon.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/16x/mod-garden/nature/logo-full.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/16x/mod-garden/nature/logo-minimal.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/16x/mod-garden/nature/logo-outline.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/1x/mod-garden/generic/icon-background.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/1x/mod-garden/generic/icon.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/1x/mod-garden/generic/logo-small-outline.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/1x/mod-garden/generic/logo-small.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/1x/mod-garden/nature/icon.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/1x/mod-garden/nature/logo-full.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/1x/mod-garden/nature/logo-minimal.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/1x/mod-garden/nature/logo-outline.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/64x/mod-garden/generic/icon-background.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/64x/mod-garden/generic/icon.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/64x/mod-garden/generic/logo-small-outline.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/64x/mod-garden/generic/logo-small.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/64x/mod-garden/nature/icon.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/64x/mod-garden/nature/logo-full.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/64x/mod-garden/nature/logo-minimal.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/64x/mod-garden/nature/logo-outline.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/8x/mod-garden/generic/icon-background.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/8x/mod-garden/generic/icon.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/8x/mod-garden/generic/logo-small-outline.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/8x/mod-garden/generic/logo-small.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/8x/mod-garden/nature/icon.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/8x/mod-garden/nature/logo-full.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/8x/mod-garden/nature/logo-minimal.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/assets/modgarden/textures/art/graphics/8x/mod-garden/nature/logo-outline.png"

[[files]]
file = "resources/resourcepack/required/mg_branding/pack.mcmeta"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/font/emoji.json"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/font/icons.json"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/ace_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/agender_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/ananas_good.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/ananas_great.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/ananas_none.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/ananas_question.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/aro_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/aroace_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/bi_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/bigender_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/blob_waaaaa.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/dead_garden.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/demi_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/femboy_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/furry_pride.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/genderfluid_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/genderflux_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/genderqueer_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/intersex_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/lesbian_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/lil_pineapple.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/mod_garden.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/nature.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/nb_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/neurodiversity_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/ohno.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/pan_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/pineapple.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/plural_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/queer_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/queer_prog_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/trans_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/uh.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/vincian_heart.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/whyfest.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/winnger.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/assets/modgarden/textures/emoji/yeefuckinghaw.png"

[[files]]
file = "resources/resourcepack/required/mg_emoji/pack.mcmeta"

[[files]]
file = "resources/resourcepack/required/mg_emoji/styled_chat_emoji.json"

[[files]]
file = "resources/resourcepack/required/twemoji.zip"

[[files]]
file = "server-icon.png"

[[files]]
file = "server.properties"

[[files]]
file = "servers.dat"

[[files]]
file = "unsup.toml"
