name = "Mod Garden: Nature"
author = "Mod Garden"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b71f5c551ffe07b0dcc37eae7e3401d6d58ce729ec6d74bcd805321ff929cc6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
unsup = "1.0.2"
unsup-experimental = "1.1.4"
unsup-stable = "1.0.2"

[options]
acceptable-game-versions = ["1.21.4"]
datapack-folder = "resources/datapack/required"
no-internal-hashes = true
