name = "Mod Garden: Nature"
author = "Mod Garden"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbcb9526e135d004b5366f8a1f31cb8e8eae607553d154d9b15b7a1751715bbf"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
unsup = "1.1.6"
unsup-experimental = "1.2.0-pre1"
unsup-stable = "1.1.6"

[options]
acceptable-game-versions = ["1.21.4"]
datapack-folder = "resources/datapack/required"
no-internal-hashes = true
