name = "Mod Garden: Nature"
author = "Mod Garden"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "595594d6e946cff8115fb79c5f4b96d6efd31bf1e315e23e6eb0f21c151a56a0"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
unsup = "1.0.2"
unsup-experimental = "1.1.4"
unsup-stable = "1.0.2"

[options]
acceptable-game-versions = ["1.21.4"]
datapack-folder = "resources/datapack/required"
no-internal-hashes = true
