[flavor_groups.axiom]
name = "Axiom EULA"
side = "client"
description = "Axiom is a building utility mod with various GUI editors and mass-build features."
[[flavor_groups.axiom.choices]]
id = "axiom_decline"
name = "Decline"
description = "You do not accept the Axiom EULA, or do not wish to install Axiom.<br><br>You can still use WorldEdit as a mass-build utility."
[[flavor_groups.axiom.choices]]
id = "axiom_accept"
name = "Accept"
description = "<b>You affirm you have read and agree to the Axiom EULA, and wish to install Axiom.</b> You can find the Axiom EULA at https://axiom.moulberry.com/eula"
[flavor_groups.enhanced_visuals]
name = "Enhanced Visuals"
side = "client"
description = "Mod Garden: Nature adds a few mods that enhance the look of the map. If you want a more vanilla experience, disable this."
[[flavor_groups.enhanced_visuals.choices]]
id = "enhanced_visuals_enable"
name = "Enable"
description = "Install a few client-side aesthetics mods including Barriers Don't Block Rain, Particle Rain, and LambdaBetterGrass."
[[flavor_groups.enhanced_visuals.choices]]
id = "enhanced_visuals_disable"
name = "Disable"
description = "Don't install Enhanced Visuals mods. Please note that Vanilla Tweaks will be enabled by default. You will have to disable it."

# [flavor_groups.worldedit]
# name = "WorldEdit"
# side = "client"
# description = "WorldEdit is a long-time server-side building utility with tool-bound wands and extensive commands.<br>Where do you intend to use WorldEdit?"
# [[flavor_groups.worldedit.choices]]
# id = "worldedit_mp"
# name = "Multiplayer"
# description = "You wish to use WorldEdit in Multiplayer. WorldEditCUI will be installed, and WorldEdit will not be installed on your client."
# [[flavor_groups.worldedit.choices]]
# id = "worldedit_sp"
# name = "Singleplayer"
# description = "You wish to use WorldEdit in Singleplayer. <b>Due to limitations in WorldEditCUI in 1.21.5, this will not install WorldEditCUI.</b>"

[metafile.axiom-client]
flavors="axiom_accept"

[metafile.barriers-dont-block-rain]
flavors="enhanced_visuals_enable"

[metafile.lambdabettergrass]
flavors="enhanced_visuals_enable"

[metafile.particle-rain]
flavors="enhanced_visuals_enable"

