# Logs what, why and where a screen could not fetch an image, if enabled.
# default: false
log_invalid_screens = true
# List of specifically allowed domains or wildcards. Overrules the blacklist.
whitelist = ["modgarden.b-cdn.net", "github.com/ModGardenEvent/nature/"]
# List of specifically disallowed domains or wildcards. Overruled by the whitelist.
blacklist = ["localhost", "*"]

